com:
  example:
    desc: 丢雷老母
    name: mojito

spring:
  redis:
    host: 127.0.0.1
    #	host: 192.168.224.225
    port: 6379
    password:

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
#      additional-exclude:

  datasource:
    name: SpikeActivity
    url: jdbc:mysql://localhost:3306/SpikeActivity?serverTimezone=UTC
    username: root
    password: 134679
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapperLocations: classpath:mapping/*.xml
